services:
  node:
    image: node:26-alpine3.23
    container_name: fighting-game-node
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    working_dir: /app
    command: ["node", "server/app.js"]

  caddy:
    image: caddy:2.11.4-alpine
    container_name: fighting-game-caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-localhost}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client:/var/www/html
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - node

volumes:
  caddy_data:
  caddy_config:
