services:
  node:
    image: node:23-alpine3.20
    container_name: node
    ports:
      - "80:3000"
      - "9229:9229"
    volumes:
      - .:/app
    working_dir: /app
    command: ash -c "npm install && node --inspect=0.0.0.0 server/app.js"
