services:
  node:
    build: .
    container_name: fighting-game-node
    volumes:
      - .:/app
    expose:
      - '3000'
    command: ["node", "server/app.js"]

  caddy:
    image: caddy:2.11.4-alpine
    container_name: fighting-game-caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      SITE_ADDRESS: ${SITE_ADDRESS:-localhost}
    volumes:
      - ./docker/caddy/data:/data
      - ./docker/caddy/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./client:/var/www/html
    depends_on:
      - node